name: "Build VI Package"
description: "Runs build_vip.ps1 to update a VIPB file and build the VI package."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: false

    - name: Pre-flight LabVIEW availability check
      shell: pwsh
      run: |
        $logDir = Join-Path -Path "${{ inputs.relative_path }}" -ChildPath "builds/logs"
        New-Item -ItemType Directory -Path $logDir -Force | Out-Null
        $logFile = Join-Path -Path $logDir -ChildPath "gcli-preflight.log"

        $gcliArgs = @(
          "--lv-ver", "${{ inputs.minimum_supported_lv_version }}",
          "--arch", "${{ inputs.supported_bitness }}",
          "--connect-timeout", "60000",
          "--kill",
          "--kill-timeout", "5000",
          "--verbose",
          "QuitLabVIEW"
        )

        Write-Host "Pre-flight command: g-cli $($gcliArgs -join ' ')"
        & g-cli @gcliArgs 2>&1 | Tee-Object -FilePath $logFile | Out-Null

        if ($LASTEXITCODE -ne 0) {
          Write-Error "Pre-flight g-cli check failed. Inspect $logFile for details."
          exit $LASTEXITCODE
        }

    - name: Run build_vip.ps1
      shell: pwsh
      env:
        DISPLAY_INFORMATION_JSON: |
          ${{ inputs.display_information_json }}
      run: |
        $displayInformationJson = $Env:DISPLAY_INFORMATION_JSON

        & "${{ github.action_path }}/build_vip.ps1" `
          -SupportedBitness ${{ inputs.supported_bitness }} `
          -RelativePath "${{ inputs.relative_path }}" `
          -VIPBPath "${{ inputs.vipb_path }}" `
          -MinimumSupportedLVVersion ${{ inputs.minimum_supported_lv_version }} `
          -LabVIEWMinorRevision ${{ inputs.labview_minor_revision }} `
          -Major ${{ inputs.major }} `
          -Minor ${{ inputs.minor }} `
          -Patch ${{ inputs.patch }} `
          -Build ${{ inputs.build }} `
          -Commit "${{ inputs.commit }}" `
          -ReleaseNotesFile "${{ inputs.release_notes_file }}" `
          -DisplayInformationJSON $displayInformationJson

    - name: Upload release notes
      uses: actions/upload-artifact@v4
      with:
        name: release-notes
        path: ${{ inputs.release_notes_file }}

    - name: Upload VI Package
      uses: actions/upload-artifact@v4
      with:
        name: vi-package
        path: builds/VI Package/*.vip

    - name: Upload g-cli logs (if present)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gcli-logs
        path: ${{ inputs.relative_path }}/builds/logs
        if-no-files-found: ignore
inputs:
  supported_bitness:
    description: '32 or 64'
    required: true
  relative_path:
    description: 'Workspace root path'
    required: true
  vipb_path:
    description: 'Path to the VIPB file (relative to workspace)'
    required: true
  minimum_supported_lv_version:
    description: 'LabVIEW major version'
    required: true
  labview_minor_revision:
    description: 'LabVIEW minor revision (0 or 3)'
    required: false
    default: '3'
  major:
    description: 'Major version component'
    required: true
  minor:
    description: 'Minor version component'
    required: true
  patch:
    description: 'Patch version component'
    required: true
  build:
    description: 'Build number'
    required: true
  commit:
    description: 'Commit identifier'
    required: true
  release_notes_file:
    description: 'Path to release notes file'
    required: true
  display_information_json:
    description: 'DisplayInformation JSON string'
    required: true
