name: "Build VI Package"
description: "Runs build_vip.ps1 to update a VIPB file and build the VI package."
outputs:
  vip_path:
    description: "Full path to the built VI package"
    value: ${{ steps.locate-vip.outputs.vip_path }}
  vip_artifact:
    description: "Artifact name (sans extension) for the built VI package"
    value: ${{ steps.locate-vip.outputs.vip_artifact }}
  release_notes_artifact:
    description: "Artifact name for the generated release notes"
    value: ${{ steps.release-notes.outputs.artifact_name }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: false

    - name: Pre-flight vipm CLI check
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $logDir = Join-Path -Path "${{ inputs.repository_path }}" -ChildPath "builds/logs"
        New-Item -ItemType Directory -Path $logDir -Force | Out-Null
        $logFile = Join-Path -Path $logDir -ChildPath "vipm-preflight.log"

        $vipm = Get-Command vipm -ErrorAction SilentlyContinue
        if (-not $vipm) {
          $msg = "vipm CLI not found on PATH; cannot build the VI package."
          $msg | Tee-Object -FilePath $logFile | Out-Null
          throw $msg
        }

        try {
          $ver = & vipm --version 2>&1
          $ver | Tee-Object -FilePath $logFile | Out-Null
          Write-Host ("vipm version: {0}" -f ($ver -join ' '))
        }
        catch {
          $_ | Out-String | Tee-Object -FilePath $logFile -Append | Out-Null
          throw "Failed to execute 'vipm --version'. Inspect $logFile for details."
        }

    - name: Clean previous VI packages
      id: clean-vip
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        function Remove-ExistingVip {
          param([string]$Dir)

          if (-not (Test-Path $Dir)) {
            Write-Host "No existing VI Package directory at '$Dir'. Creating it..."
            New-Item -ItemType Directory -Path $Dir -Force | Out-Null
            return $Dir
          }

          $existingVip = Get-ChildItem -Path $Dir -Filter *.vip -File -Recurse
          if (-not $existingVip) {
            Write-Host "No preexisting .vip files found at '$Dir'."
            return $Dir
          }

          Write-Host "Found existing .vip files before build:"
          $existingVip | ForEach-Object { Write-Host " - $($_.FullName)" }
          Write-Host "Deleting existing .vip files prior to build..."

          $failed = $false
          foreach ($file in $existingVip) {
            try {
              Remove-Item -LiteralPath $file.FullName -Force -ErrorAction Stop
            }
            catch {
              $failed = $true
              Write-Warning ("Failed to delete {0}: {1}" -f $file.FullName, $_.Exception.Message)
            }
          }

          if ($failed) {
            throw "One or more old .vip files could not be removed; aborting before build."
          }

          Write-Host ("Deleted {0} .vip file(s) prior to build." -f $existingVip.Count)
          return $Dir
        }

        $vipDir = Join-Path -Path "${{ inputs.repository_path }}" -ChildPath "builds/VI Package"
        $vipDir = Remove-ExistingVip -Dir $vipDir

        "vip_dir=$vipDir" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append

    - name: Run build_vip.ps1
      shell: pwsh
      env:
        DISPLAY_INFORMATION_JSON: |
          ${{ inputs.display_information_json }}
      run: |
        $displayInformationJson = $Env:DISPLAY_INFORMATION_JSON

        $repo = "${{ inputs.repository_path }}"
        $candidates = @(
          (Join-Path $repo 'scripts/get-package-lv-version.ps1'),
          (Join-Path '${{ github.workspace }}' 'scripts/get-package-lv-version.ps1')
        )
        $lvScript = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
        if (-not $lvScript) {
          throw "Unable to locate get-package-lv-version.ps1 under '$repo/scripts' or '${{ github.workspace }}/scripts'."
        }

        $lvVer = pwsh -NoProfile -File $lvScript -RepositoryPath $repo

        $splat = @{
          SupportedBitness      = ${{ inputs.supported_bitness }}
          RepositoryPath        = "${{ inputs.repository_path }}"
          VIPBPath              = "${{ inputs.vipb_path }}"
          Package_LabVIEW_Version = $lvVer
          LabVIEWMinorRevision  = ${{ inputs.labview_minor_revision }}
          Major                 = ${{ inputs.major }}
          Minor                 = ${{ inputs.minor }}
          Patch                 = ${{ inputs.patch }}
          Build                 = ${{ inputs.build }}
          Commit                = "${{ inputs.commit }}"
          ReleaseNotesFile      = "${{ inputs.release_notes_file }}"
          DisplayInformationJSON= $displayInformationJson
        }

        if ("${{ inputs.simulate }}" -eq "true") {
          $splat.Simulate = $true
        }
        if ("${{ inputs.skip_ppl_check }}" -eq "true") {
          $splat.SkipPPLCheck = $true
        }

        & "${{ github.workspace }}/scripts/build-vip/build_vip.ps1" @splat

    - name: Dump vipm build logs on failure
      if: failure()
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $logDir = Join-Path -Path "${{ inputs.repository_path }}" -ChildPath "builds/logs"
        if (-not (Test-Path $logDir)) {
          Write-Host "No log directory found at $logDir."
          exit 0
        }

        $logs = Get-ChildItem -Path $logDir -Filter "vipm-build-attempt-*.log" -File | Sort-Object Name
        if (-not $logs) {
          $logs = Get-ChildItem -Path $logDir -Filter "vipm-preflight.log" -File | Sort-Object Name
        }
        if (-not $logs) {
          Write-Host "No vipm build logs found under $logDir."
          exit 0
        }

        foreach ($log in $logs) {
          Write-Host ("---- vipm build log ({0}) ----" -f $log.FullName)
          Get-Content -Path $log.FullName | ForEach-Object { Write-Host $_ }
          Write-Host ("---- end vipm build log ({0}) ----" -f $log.FullName)
        }
    
    - name: Prepare release notes artifact
      id: release-notes
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $source = "${{ inputs.release_notes_file }}"
        if (-not (Test-Path $source)) {
          Write-Error "Release notes file not found at $source."
          exit 1
        }

        $dir = Split-Path -Parent $source
        $repoName = Split-Path -Path "${{ inputs.repository_path }}" -Leaf
        if ([string]::IsNullOrWhiteSpace($repoName)) {
          $repoName = "labview-icon-editor"
        }
        $stem = "{0}_{1}bit_{2}.{3}.{4}.{5}" -f $repoName,"${{ inputs.supported_bitness }}","${{ inputs.major }}","${{ inputs.minor }}","${{ inputs.patch }}","${{ inputs.build }}"
        $destName = "release_notes_{0}.md" -f $stem
        $artifactName = "release_notes_{0}" -f $stem
        $destPath = Join-Path -Path $dir -ChildPath $destName

        Copy-Item -LiteralPath $source -Destination $destPath -Force
        Write-Host ("Release notes artifact prepared at {0}" -f $destPath)

        "artifact_path=$destPath" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        "artifact_name=$artifactName" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append

    - name: Locate built VI package
      id: locate-vip
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $searchRoot = "${{ steps.clean-vip.outputs.vip_dir }}"
        $vipFiles = Get-ChildItem -Path $searchRoot -Filter *.vip -File -Recurse | Sort-Object LastWriteTime -Descending

        if (-not $vipFiles) {
          Write-Error "No .vip file found under '$searchRoot'."
          exit 1
        }

        if ($vipFiles.Count -gt 1) {
          Write-Warning ("Multiple .vip files found; selecting most recent (by LastWriteTime). Files:`n{0}" -f ($vipFiles | ForEach-Object { " - $($_.FullName)" } | Out-String))
          if ("${{ inputs.fail_on_multiple_vips }}" -eq "true") {
            Write-Error "More than one .vip was produced after cleanup."
            exit 1
          }
        }

        $vip = $vipFiles[0]
        Write-Host ("Selected .vip: {0}" -f $vip.FullName)

        $repoName = Split-Path -Path "${{ inputs.repository_path }}" -Leaf
        if ([string]::IsNullOrWhiteSpace($repoName)) {
          $repoName = "labview-icon-editor"
        }
        $stem = "{0}_{1}bit_{2}.{3}.{4}.{5}" -f $repoName,"${{ inputs.supported_bitness }}","${{ inputs.major }}","${{ inputs.minor }}","${{ inputs.patch }}","${{ inputs.build }}"
        $targetName = "$stem.vip"
        $targetPath = Join-Path -Path $vip.DirectoryName -ChildPath $targetName

        if ($vip.FullName -ne $targetPath) {
          Write-Host ("Renaming {0} -> {1}" -f $vip.Name, $targetName)
          if (Test-Path $targetPath) { Remove-Item -LiteralPath $targetPath -Force }
          Move-Item -LiteralPath $vip.FullName -Destination $targetPath -Force
        }

        "vip_path=$targetPath" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        "vip_name=$targetName" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        "vip_artifact=$stem"   | Out-File -FilePath $Env:GITHUB_OUTPUT -Append

    - name: Upload release notes
      id: upload-release-notes
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.release-notes.outputs.artifact_name }}
        path: ${{ steps.release-notes.outputs.artifact_path }}
        compression-level: 0
        if-no-files-found: ignore

    - name: Upload VI Package (attempt 1)
      if: success()
      id: upload-vip-1
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.locate-vip.outputs.vip_artifact }}
        path: ${{ steps.locate-vip.outputs.vip_path }}
        if-no-files-found: ignore

    - name: Upload VI Package (backoff before retry)
      if: steps.upload-vip-1.outcome != 'success'
      shell: pwsh
      run: Start-Sleep -Seconds 10

    - name: Upload VI Package (attempt 2)
      if: steps.upload-vip-1.outcome != 'success'
      id: upload-vip-2
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.locate-vip.outputs.vip_artifact }}
        path: ${{ steps.locate-vip.outputs.vip_path }}
        if-no-files-found: ignore

    - name: Upload VI Package (final attempt)
      if: steps.upload-vip-1.outcome != 'success' && steps.upload-vip-2.outcome != 'success'
      id: upload-vip-3
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.locate-vip.outputs.vip_artifact }}
        path: ${{ steps.locate-vip.outputs.vip_path }}
        if-no-files-found: ignore

    - name: Fail if VIP upload failed
      if: steps.upload-vip-1.outcome != 'success' && steps.upload-vip-2.outcome != 'success' && steps.upload-vip-3.outcome != 'success'
      shell: pwsh
      run: |
        Write-Error "VIP artifact upload failed after 3 attempts (check network/ECONNRESET)."

    - name: Upload vipm logs (if present)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.locate-vip.outputs.vip_artifact }}-vipm-logs
        path: ${{ inputs.repository_path }}/builds/logs
        if-no-files-found: ignore

    - name: Print release notes
      if: always()
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $path = "${{ steps.release-notes.outputs.artifact_path }}"
        if (-not (Test-Path $path)) {
          Write-Host "Release notes file not found at $path."
          exit 0
        }
        Write-Host "---- Release notes (${path}) ----"
        Get-Content -Path $path | ForEach-Object { Write-Host $_ }
        Write-Host "---- end release notes ----"
inputs:
  supported_bitness:
    description: '32 or 64'
    required: true
  repository_path:
    description: 'Workspace root path'
    required: true
  vipb_path:
    description: 'Path to the VIPB file (relative to workspace). Leave blank to auto-discover a single .vipb under repository_path.'
    required: false
    default: ''
  labview_minor_revision:
    description: 'LabVIEW minor revision (0 or 3)'
    required: false
    default: '3'
  major:
    description: 'Major version component'
    required: true
  minor:
    description: 'Minor version component'
    required: true
  patch:
    description: 'Patch version component'
    required: true
  build:
    description: 'Build number'
    required: true
  commit:
    description: 'Commit identifier'
    required: true
  release_notes_file:
    description: 'Path to release notes file'
    required: true
  display_information_json:
    description: 'DisplayInformation JSON string'
    required: true
  fail_on_multiple_vips:
    description: 'If true, fail when multiple .vip files exist after the build step'
    required: false
    default: 'true'
  simulate:
    description: 'If true, run preflights only and skip vipm build'
    required: false
    default: 'false'
  skip_ppl_check:
    description: 'If true, do not require staged PPL variants (for simulate/dry-run only)'
    required: false
    default: 'false'
