name: "Apply VIPC Dependencies"
description: "Runs ApplyVIPC.ps1 to install runner dependencies for a given LabVIEW version/bitness."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run ApplyVIPC.ps1
      id: apply
      shell: pwsh
      run: |
        & "${{ github.action_path }}/ApplyVIPC.ps1" `
          -Package_LabVIEW_Version ${{ inputs.package_labview_version }} `
          -SupportedBitness ${{ inputs.supported_bitness }} `
          -RepositoryPath "${{ inputs.repository_path }}" `
          -VIPCPath "${{ inputs.vipc_path }}"
outputs:
  summary-json:
    description: 'Path to the apply-vipc summary JSON (package diff and verification results).'
    value: ${{ steps.apply.outputs.summary-json }}
inputs:
  package_labview_version:
    description: 'LabVIEW version to target (derived from VIPB)'
    required: true
  supported_bitness:
    description: '32 or 64'
    required: true
  repository_path:
    description: 'Workspace root path'
    required: true
  vipc_path:
    description: 'Path under repo for the .vipc file (relative to workspace)'
    required: true
