name: "Apply VIPC Dependencies"
description: "Runs ApplyVIPC.ps1 to install runner dependencies for a given LabVIEW version/bitness."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run ApplyVIPC.ps1
      shell: pwsh
      run: |
        & "${{ github.action_path }}/ApplyVIPC.ps1" `
          -Package_LabVIEW_Version ${{ inputs.minimum_supported_lv_version }} `
          -VIP_LVVersion ${{ inputs.vip_lv_version }} `
          -SupportedBitness ${{ inputs.supported_bitness }} `
          -RepositoryPath "${{ inputs.repository_path }}" `
          -VIPCPath "${{ inputs.vipc_path }}"
inputs:
  minimum_supported_lv_version:
    description: 'LabVIEW major version (e.g. 2021)'
    required: true
  vip_lv_version:
    description: 'VIPC LV version (usually same as minimum supported)'
    required: true
  supported_bitness:
    description: '32 or 64'
    required: true
  repository_path:
    description: 'Workspace root path'
    required: true
  vipc_path:
    description: 'Path under repo for the .vipc file (relative to workspace)'
    required: true
