name: "Add LabVIEW INI Token"
description: "Runs AddTokenToLabVIEW.ps1 to add a Localhost.LibraryPaths token to the LabVIEW INI file."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run AddTokenToLabVIEW.ps1
      shell: pwsh
      run: |
        $lvVer = pwsh -NoProfile -File "${{ github.workspace }}/scripts/get-package-lv-version.ps1" -RepositoryPath "${{ inputs.repository_path }}"
        & "${{ github.workspace }}/scripts/add-token-to-labview/AddTokenToLabVIEW.ps1" \
          -Package_LabVIEW_Version $lvVer \
          -SupportedBitness ${{ inputs.supported_bitness }} \
          -RepositoryPath "${{ inputs.repository_path }}"
inputs:
  supported_bitness:
    description: '32 or 64'
    required: true
  repository_path:
    description: 'Workspace root path'
    required: true
