name: "Run Unit Tests"
description: "Runs RunUnitTests.ps1 to execute LabVIEW unit tests via g-cli."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run RunUnitTests.ps1
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Set-StrictMode -Version Latest

        $repo = Resolve-Path "${{ inputs.repository_path }}"
        $lvVer = pwsh -NoProfile -File "$repo/scripts/resolve-lv-version.ps1" -RepositoryPath $repo

        & "${{ github.action_path }}/RunUnitTests.ps1" `
          -Package_LabVIEW_Version $lvVer `
          -SupportedBitness ${{ inputs.supported_bitness }}
inputs:
  repository_path:
    description: 'Workspace root path'
    required: true
  supported_bitness:
    description: '32 or 64'
    required: true
