name: "Run Unit Tests"
description: "Runs RunUnitTests.ps1 to execute LabVIEW unit tests via g-cli."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run RunUnitTests.ps1
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Set-StrictMode -Version Latest

        $repo = Resolve-Path "${{ inputs.repository_path }}"
        $candidates = @(
          Join-Path $repo 'scripts/get-package-lv-version.ps1'),
          Join-Path $repo '.github/scripts/get-package-lv-version.ps1'
        ) -as [string[]]

        $lvScript = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
        if (-not $lvScript) {
          throw "Unable to locate get-package-lv-version.ps1 under '$repo/scripts' or '$repo/.github/scripts'."
        }

        $lvVer = pwsh -NoProfile -File $lvScript -RepositoryPath $repo
        if (-not $lvVer) {
          throw "Failed to resolve LabVIEW version from VIPB."
        }

        & "${{ github.action_path }}/RunUnitTests.ps1" `
          -Package_LabVIEW_Version $lvVer `
          -SupportedBitness ${{ inputs.supported_bitness }}
inputs:
  repository_path:
    description: 'Workspace root path'
    required: true
  supported_bitness:
    description: '32 or 64'
    required: true
