name: "Set Development Mode"
description: "Runs Set_Development_Mode.ps1 to configure the repo for development."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Set_Development_Mode.ps1
      shell: pwsh
      run: |
        & "${{ github.action_path }}/Set_Development_Mode.ps1" \
          -RepositoryPath "${{ inputs.repository_path }}" \
          -MinimumSupportedLVVersion "${{ inputs.minimum_supported_lv_version }}"
inputs:
  repository_path:
    description: 'Workspace root path'
    required: true
  minimum_supported_lv_version:
    description: 'LabVIEW major.minor to target (e.g., 2021, 2023)'
    required: false
    default: "2021"
