name: Analyze VI Package
description: "Run Pester policy tests against a LabVIEW VI Package (.vip) by reading the package directly."
inputs:
  vip_artifact_path:
    description: "Path to the built .vip file to analyze (direct file path recommended)"
    required: true
  min_labview:
    description: "Minimum LabVIEW version (major.minor) the package must support (e.g., 21.0)"
    required: false
    default: "21.0"
runs:
  using: "composite"
  steps:
    - id: analyze
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Set-StrictMode -Off
        $work = $PSScriptRoot
        Set-Location $work
        # Ensure Pester 5.7.1 (align with local runner to avoid v6 alpha differences)
        $desiredVersion = [version]'5.7.1'
        Remove-Module Pester -ErrorAction SilentlyContinue
        $mod = Get-Module -ListAvailable -Name Pester | Where-Object { $_.Version -eq $desiredVersion } | Select-Object -First 1
        if (-not $mod) {
          Install-Module Pester -RequiredVersion $desiredVersion -Scope CurrentUser -Force -SkipPublisherCheck
          $mod = Get-Module -ListAvailable -Name Pester | Where-Object { $_.Version -eq $desiredVersion } | Select-Object -First 1
        }
        if (-not $mod) {
          throw "Pester $desiredVersion not available even after install."
        }
        Import-Module $mod.Path -Force

        $tests = Join-Path $work "Analyze-VIP.Tests.ps1"
        $results = Join-Path $work "pester-results.xml"
        $env:VIP_PATH = "${{ inputs.vip_artifact_path }}"
        $env:MIN_LV_VERSION = "${{ inputs.min_labview }}"
        $config = [PesterConfiguration]::Default
        $config.Run.Path = @($tests)
        $config.Run.PassThru = $true
        $config.Output.Verbosity = 'Detailed'
        $config.TestResult.Enabled = $true
        $config.TestResult.OutputPath = $results
        Invoke-Pester -Configuration $config
        "junit=$results" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
outputs:
  junit:
    description: "Path to the JUnit XML test results file"
    value: ${{ steps.analyze.outputs.junit }}
