name: Analyze VI Package
description: "Run Pester policy tests against a LabVIEW VI Package (.vip) by reading the package directly."
inputs:
  vip_path:
    description: "Path to the .vip file to analyze"
    required: true
  min_labview:
    description: "Minimum LabVIEW version (major.minor) the package must support (e.g., 21.0)"
    required: false
    default: "21.0"
runs:
  using: "composite"
  steps:
    - id: analyze
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Set-StrictMode -Version Latest
        $work = $PSScriptRoot
        Set-Location $work
        # Ensure Pester 5+
        $needInstall = $true
        try {
          $mod = Get-Module -ListAvailable -Name Pester | Sort-Object Version -Descending | Select-Object -First 1
          if ($mod -and $mod.Version.Major -ge 5) { $needInstall = $false }
        } catch {}
        if ($needInstall) {
          Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck
        }

        $tests = Join-Path $work "Analyze-VIP.Tests.ps1"
        $results = Join-Path $work "pester-results.xml"
        Invoke-Pester -Script @{
            Path = $tests
            Parameters = @{
              VipPath = "${{ inputs.vip_path }}"
              MinLabVIEW = "${{ inputs.min_labview }}"
            }
          } -CI -Output Detailed -PassThru -Configuration @{
            Run = @{ PassThru = $true }
            Output = @{ Verbosity = 'Detailed' }
            TestResult = @{ Enabled = $true; OutputPath = $results }
          }
        "junit=$results" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
outputs:
  junit:
    description: "Path to the JUnit XML test results file"
    value: ${{ steps.analyze.outputs.junit }}
