name: "Missing In Project"
description: >
  Executes MissinInProjectCLI.vi (bundled with this action) via g‑cli,
  pointing at a user‑supplied *.lvproj* (default: lv_icon.lvproj in repo root).
  Fails instantly on any missing file and exports:
    • passed        (Boolean)  
    • missing-files (String)

branding:
  icon: check-circle
  color: purple

inputs:
  lv-ver:
    description: "LabVIEW version (e.g. '2021')."
    required: true
  arch:
    description: "Bitness (32 or 64)."
    required: true
  project-file:
    description: >
      Path to the .lvproj to inspect. If empty, auto-detect the only .lvproj under the repo.
    required: false
    default: ""

outputs:
  passed:
    description: "True if VI reported success."
    value: ${{ steps.run_vi.outputs.passed }}
  missing-files:
    description: "Comma-separated list of missing files."
    value: ${{ steps.run_vi.outputs.missing-files }}
  gcli-log:
    description: "Path to the saved g-cli log (if generated)."
    value: ${{ steps.run_vi.outputs.gcli-log }}
  meta-path:
    description: "Path to the saved metadata JSON (if generated)."
    value: ${{ steps.run_vi.outputs.meta-path }}

runs:
  using: composite
  steps:

    - name: Validate inputs
      shell: pwsh
      run: |
        if ([string]::IsNullOrWhiteSpace('${{ inputs.lv-ver }}')) {
          throw "Missing input 'lv-ver'; must be a non-empty LabVIEW version (e.g. 2021)."
        }
        if ([string]::IsNullOrWhiteSpace('${{ inputs.arch }}')) {
          throw "Missing input 'arch'; must be '32' or '64'."
        }
        if ('${{ inputs.arch }}' -ne '32' -and '${{ inputs.arch }}' -ne '64') {
          throw "Invalid 'arch' value '${{ inputs.arch }}'; must be '32' or '64'."
        }

    - name: Resolve project file path (auto-detect when omitted)
      id: resolve
      shell: pwsh
      run: |
        $pf = '${{ inputs.project-file }}'
        if (-not [string]::IsNullOrWhiteSpace($pf)) {
          if (-not [System.IO.Path]::IsPathRooted($pf)) {
            $pf = Join-Path $Env:GITHUB_WORKSPACE $pf
          }
          if (-not (Test-Path $pf)) {
            throw "Project file not found: $pf"
          }
          echo "projFile=$pf" >> $Env:GITHUB_OUTPUT
          Write-Host "ℹ️  Using project file: $pf"
          exit 0
        }

        $candidates = Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Filter *.lvproj -File -Recurse
        if (-not $candidates) {
          throw "No .lvproj files found under $Env:GITHUB_WORKSPACE. Provide inputs.project-file."
        }

        # Prefer a root-level project if multiple are present
        $workspaceRoot = (Resolve-Path $Env:GITHUB_WORKSPACE).Path
        $rootProjects = $candidates | Where-Object { $_.Directory.FullName -eq $workspaceRoot }
        if ($rootProjects.Count -eq 1) {
          $candidates = @($rootProjects[0])
        }
        elseif ($rootProjects.Count -gt 1) {
          $candidates = $rootProjects
        }

        if ($candidates.Count -gt 1) {
          $list = $candidates | ForEach-Object { " - $($_.FullName)" } | Out-String
          throw "Multiple .lvproj files found; set inputs.project-file to disambiguate. Candidates:`n$list"
        }

        $pf = $candidates[0].FullName
        echo "projFile=$pf" >> $Env:GITHUB_OUTPUT
        Write-Host "ℹ️  Auto-detected project file: $pf"

    - name: Invoke PS1 wrapper
      id: run_vi
      shell: pwsh
      run: |
        & "$Env:GITHUB_ACTION_PATH\Invoke-MissingInProjectCLI.ps1" `
          -LVVersion   "${{ inputs.lv-ver }}" `
          -Arch        "${{ inputs.arch }}" `
          -ProjectFile "${{ steps.resolve.outputs.projFile }}"
