name: "Auto Issue Branch Creator"
description: "Creates a branch for an issue when all required metadata is present."
inputs:
  base_branch:
    description: "Base branch to create new branches from"
    required: false
outputs:
  branch:
    description: "Name of the created branch"
    value: ${{ steps.create_branch.outputs.branch_name }}
  version_bump:
    description: "Semantic version bump derived from issue type"
    value: ${{ steps.check.outputs.version_bump }}
runs:
  using: "composite"
  steps:
    - name: Gather and validate issue data
      id: check
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.token }}
        script: |
          const issue = context.payload.issue;
          if (!issue) {
            core.setFailed('This action only runs on issue events.');
            return;
          }
          const repo = context.repo;
          const labels = issue.labels.map(l => l.name.toLowerCase());
          const milestoneSet = !!issue.milestone;
          const hasAssignee = issue.assignees && issue.assignees.length > 0;
          const title = issue.title || '';
          const titleOk = title.length > 0 && title.length <= 30;
          const types = ['feature','bug','task'];
          const typeLabel = labels.find(l => types.includes(l));
          const { versionBumpFromType } = require(process.env.GITHUB_ACTION_PATH + '/utils.js');
          const versionBump = versionBumpFromType(typeLabel);
          let hasProject = false;
          try {
            const data = await github.graphql(
              `query($owner:String!,$repo:String!,$number:Int!){
                 repository(owner:$owner,name:$repo){
                   issue(number:$number){
                     projectItems(first:1){ totalCount }
                   }
                 }
               }`,
              {owner: repo.owner, repo: repo.repo, number: issue.number}
            );
            hasProject = data.repository.issue.projectItems.totalCount > 0;
          } catch (e) {
            core.warning('Failed to verify project assignment: ' + e.message);
          }
          const conditionsMet = titleOk && milestoneSet && hasAssignee && typeLabel && hasProject;
          core.setOutput('conditions_met', conditionsMet);
          core.setOutput('issue_type', typeLabel || '');
          core.setOutput('version_bump', versionBump);
          if (!conditionsMet) {
            core.info('Conditions not met. Skipping branch creation.');
          }
    - name: Create branch
      id: create_branch
      if: ${{ steps.check.outputs.conditions_met == 'true' && steps.check.outputs.issue_type != 'task' && github.event.repository.fork != true }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.token }}
        script: |
          const issue = context.payload.issue;
          const repo = context.repo;
          const rawTitle = issue.title;
          const { buildBranchName } = require(process.env.GITHUB_ACTION_PATH + '/utils.js');
          const branch = buildBranchName(issue.number, rawTitle);
          let base = `${{ inputs.base_branch || '' }}`;
          if (!base) base = context.payload.repository.default_branch;
          const baseRef = await github.rest.git.getRef({
            owner: repo.owner,
            repo: repo.repo,
            ref: `heads/${base}`
          });
          await github.rest.git.createRef({
            owner: repo.owner,
            repo: repo.repo,
            ref: `refs/heads/${branch}`,
            sha: baseRef.data.object.sha
          });
          core.setOutput('branch_name', branch);
    - name: Comment on issue
      if: ${{ steps.check.outputs.conditions_met == 'true' && steps.check.outputs.issue_type != 'task' && github.event.repository.fork != true }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.token }}
        script: |
          const branch = `${{ steps.create_branch.outputs.branch_name }}`;
          const issueNum = context.payload.issue.number;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNum,
            body: `A new branch \`${branch}\` has been created for this issue.`
          });
