name: "Build Packed Library"
description: "Runs Build_lvlibp.ps1 to create the editor packed library."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Build_lvlibp.ps1
      shell: pwsh
      run: |
        $repo = "${{ inputs.repository_path }}"
        if (-not $repo) {
          $relative = "${{ inputs.relative_path }}"
          if ($relative) {
            $repo = Join-Path $env:GITHUB_WORKSPACE $relative
          }
          else {
            $repo = $env:GITHUB_WORKSPACE
          }
        }

        if (-not (Test-Path $repo)) {
          throw "Repository path '$repo' does not exist."
        }

        $lvVer = "${{ inputs.minimum_supported_lv_version }}"
        if (-not $lvVer) {
          $candidates = @(
            "$repo/scripts/get-package-lv-version.ps1",
            "$env:GITHUB_WORKSPACE/scripts/get-package-lv-version.ps1"
          )
          $verScript = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
          if (-not $verScript) {
            throw "Unable to locate get-package-lv-version.ps1. Checked: $($candidates -join ', ')"
          }
          $lvVer = pwsh -NoProfile -File $verScript -RepositoryPath $repo
        }

        & "${{ github.workspace }}/scripts/build-lvlibp/Build_lvlibp.ps1" `
          -Package_LabVIEW_Version $lvVer `
          -SupportedBitness ${{ inputs.supported_bitness }} `
          -RepositoryPath $repo `
          -Major ${{ inputs.major }} `
          -Minor ${{ inputs.minor }} `
          -Patch ${{ inputs.patch }} `
          -Build ${{ inputs.build }} `
          -Commit "${{ inputs.commit }}"
inputs:
  minimum_supported_lv_version:
    description: 'Minimum LabVIEW version to build against. If empty, get-package-lv-version.ps1 is used.'
    required: false
    default: ''
  supported_bitness:
    description: '32 or 64'
    required: true
  relative_path:
    description: 'Path to the repository relative to GITHUB_WORKSPACE (alternative to repository_path).'
    required: false
    default: ''
  repository_path:
    description: 'Workspace root path'
    required: false
  major:
    description: 'Major version component'
    required: true
  minor:
    description: 'Minor version component'
    required: true
  patch:
    description: 'Patch version component'
    required: true
  build:
    description: 'Build number'
    required: true
  commit:
    description: 'Commit identifier'
    required: true
