name: "Build Packed Library"
description: "Runs Build_lvlibp.ps1 to create the editor packed library."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Build_lvlibp.ps1
      shell: pwsh
      run: |
        $candidates = @(
          "$env:GITHUB_WORKSPACE/scripts/get-package-lv-version.ps1",
          "$env:GITHUB_WORKSPACE/.github/scripts/get-package-lv-version.ps1",
          "${{ github.action_path }}/../../scripts/get-package-lv-version.ps1"
        )
        $verScript = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
        if (-not $verScript) {
          throw "Unable to locate get-package-lv-version.ps1. Checked: $($candidates -join ', ')"
        }

        $lvVer = pwsh -NoProfile -File $verScript -RepositoryPath "${{ inputs.repository_path }}"
        & "${{ github.action_path }}/Build_lvlibp.ps1" `
          -Package_LabVIEW_Version $lvVer `
          -SupportedBitness ${{ inputs.supported_bitness }} `
          -RepositoryPath "${{ inputs.repository_path }}" `
          -Major ${{ inputs.major }} `
          -Minor ${{ inputs.minor }} `
          -Patch ${{ inputs.patch }} `
          -Build ${{ inputs.build }} `
          -Commit "${{ inputs.commit }}"
inputs:
  supported_bitness:
    description: '32 or 64'
    required: true
  repository_path:
    description: 'Workspace root path'
    required: true
  major:
    description: 'Major version component'
    required: true
  minor:
    description: 'Minor version component'
    required: true
  patch:
    description: 'Patch version component'
    required: true
  build:
    description: 'Build number'
    required: true
  commit:
    description: 'Commit identifier'
    required: true
