name: "Restore LabVIEW Setup"
description: "Runs RestoreSetupLVSource.ps1 to revert prepared sources back to packaged state."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run RestoreSetupLVSource.ps1
      shell: pwsh
      run: |
        $lvVer = pwsh -NoProfile -File "${{ github.workspace }}/scripts/get-package-lv-version.ps1" -RepositoryPath "${{ inputs.repository_path }}"
        & "${{ github.workspace }}/scripts/restore-setup-lv-source/RestoreSetupLVSource.ps1" \
          -Package_LabVIEW_Version $lvVer \
          -SupportedBitness ${{ inputs.supported_bitness }} \
          -RepositoryPath "${{ inputs.repository_path }}" \
          -LabVIEW_Project "${{ inputs.labview_project }}" \
          -Build_Spec "${{ inputs.build_spec }}"
inputs:
  supported_bitness:
    description: '32 or 64'
    required: true
  repository_path:
    description: 'Workspace root path'
    required: true
  labview_project:
    description: 'LabVIEW project name (without extension)'
    required: true
  build_spec:
    description: 'Build specification name'
    required: true
