name: "Close LabVIEW"
description: "Runs Close_LabVIEW.ps1 to gracefully shut down a LabVIEW instance."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: false

    - name: Run Close_LabVIEW.ps1
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $repo = "${{ inputs.repository_path }}"
        if ([string]::IsNullOrWhiteSpace($repo)) {
          $repo = $env:GITHUB_WORKSPACE
        }
        $candidates = @(
          (Join-Path $repo 'scripts/get-package-lv-version.ps1'),
          (Join-Path $repo '.github/scripts/get-package-lv-version.ps1')
        )
        $lvScript = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
        if (-not $lvScript) {
          throw "Unable to locate get-package-lv-version.ps1 under '$repo/scripts' or '$repo/.github/scripts'."
        }
        $lvVer = pwsh -NoProfile -File $lvScript -RepositoryPath $repo
        & "${{ github.action_path }}/Close_LabVIEW.ps1" `
          -Package_LabVIEW_Version $lvVer `
          -SupportedBitness ${{ inputs.supported_bitness }}
inputs:
  minimum_supported_lv_version:
    description: 'Minimum LabVIEW version allowed to run'
    required: false
  repository_path:
    description: 'Workspace root path'
    required: true
  supported_bitness:
    description: '32 or 64'
    required: true
