name: "Close LabVIEW"
description: "Runs Close_LabVIEW.ps1 to gracefully shut down a LabVIEW instance."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: false

    - name: Run Close_LabVIEW.ps1
      shell: pwsh
      run: |
        $lvVer = pwsh -NoProfile -File "${{ github.action_path }}/../../scripts/get-package-lv-version.ps1" -RepositoryPath "${{ inputs.repository_path }}"
        & "${{ github.action_path }}/Close_LabVIEW.ps1" `
          -Package_LabVIEW_Version $lvVer `
          -SupportedBitness ${{ inputs.supported_bitness }}
inputs:
  repository_path:
    description: 'Workspace root path'
    required: true
  supported_bitness:
    description: '32 or 64'
    required: true
